### ISSUE TITLE
BUG in Build and Release.yml

### ISSUE THREAD

**Issue by nilay-coder** [aiyu-ayaan/BIT-App#78]
Error
```
      - name: Upload Bundle
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          retention-days: 1
          path: bitapp/build/outputs/bundle/global/bitapp-global-release.aab
```
Solution
```
      - name: Upload Bundle
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          retention-days: 1
          path: bitapp/build/outputs/bundle/globalRelease/bitapp-global-release.aab
```
